homepage/urls.py
from django.urls import path, include
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('add_status', views.add_status_view, name="add_status"),
    path('del_status/<int:id>', views.del_status_view, name='del_status'),
]

lab7/urls.py
from django.urls import path, include
from . import views

app_name = 'lab7'

urlpatterns = [
    path('', views.lab7_view, name='view_lab7'),
]

lab8/urls.py
from django.urls import path, include
from . import views

app_name = 'lab8'

urlpatterns = [
    path('', views.lab8_view, name='view_lab8'),
]

lab9/urls.py
from django.urls import path, include
from . import views

app_name = 'lab9'

urlpatterns = [
	path('', views.lab9_view, name = "view_lab9"),
	path('signup/', views.signup_view, name = "signup"),
	path('login/', views.login_view, name = "login"),
	path('logout/', views.logout_view, name = "logout"),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('lab7/', include('lab7.urls')),
    path('lab8/', include('lab8.urls')),
    path('lab9/', include('lab9.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	title = models.CharField(max_length=30)
	description = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

lab7/models.py
from django.db import models

# Create your models here.

lab8/models.py
from django.db import models

# Create your models here.

lab9/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Please do not leave this empty!',
    }
    title_attrs = {
        'type': 'text',
        'class': 'status-form-input',
        'placeholder':'Enter new status...'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 8,
        'class': 'status-form-textarea',
        'placeholder':'Enter status description...'
    }

    title = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=title_attrs))
    description = forms.CharField(label='', required=True, max_length=300, widget=forms.Textarea(attrs=description_attrs))

lab9/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Status
from .forms import Status_Form

# Create your views here.
response = {}

def index_view(request):
	status = Status.objects.all().order_by('-created_date')
	response['status'] = status
	response['status_form'] = Status_Form
	return render(request, 'index.html', response)

def add_status_view(request):
	form = Status_Form(request.POST or None)

	if( (request.method == 'POST') and form.is_valid() ):
		response['title'] = request.POST['title']
		response['description'] = request.POST['description']
		status = Status(title=response['title'], description=response['description'])
		status.save()
		return HttpResponseRedirect('/')
	else:
		return HttpResponseRedirect('/')

def del_status_view(request, id):
	Status.objects.get(pk=id).delete()
	return HttpResponseRedirect('/')

lab7/views.py
from django.shortcuts import render

# Create your views here.

def lab7_view(request):
    return render(request, 'lab7.html')

lab8/views.py
from django.shortcuts import render

# Create your views here.

def lab8_view(request):
    return render(request, 'lab8.html')

lab9/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm

# Create your views here.
def signup_view(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			user = form.save()
			login(request, user)
			return redirect('lab9:view_lab9')
	else:
		form = UserRegisterForm()
	return render(request, 'signup_lab9.html', {'form':form})

def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request, user)
			return redirect('lab9:view_lab9')
	else:
		form = AuthenticationForm()
	return render(request, 'login_lab9.html', {'form':form})

@login_required(login_url="/lab9/login/")
def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('lab9:login')

@login_required(login_url="/lab9/login/")
def lab9_view(request):
	return render(request, 'hello_lab9.html')

homepage/templates/index.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html lang="en">
    
  <head>
        
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- App CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/home_style.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">

    <!-- Link to Quicksand Font -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

    <!-- Website Title  -->
    <title>PPW Story 6 | Primo G U</title>

  </head>

  <body>

    <!-- Bootstrap Sticky Navbar -->
    <nav class="navbar navbar-expand-sm bg-light navbar-light sticky-top">

        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar Links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto" style="margin-right: 30px;">

                <li class="nav-item">
                    <a class="nav-link active disabled" href="{% url 'homepage:index' %}"
                    style="font-family: Quicksand; font-size: 20px;"> 
                        Story 6
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lab7:view_lab7' %}" style="font-family: Quicksand; font-size: 20px;"> 
                        Story 7
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lab8:view_lab8' %}" style="font-family: Quicksand; font-size: 20px;"> 
                        Story 8
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lab9:view_lab9' %}" style="font-family: Quicksand; font-size: 20px;">
                        Story 9
                    </a>
                </li>

            </ul>
        </div>

    </nav>

    <h1 class="main-title"><strong>HALO! APA KABAR?</strong></h1>

    <section name="input-list" id="input-list">
        <div class="container">
            <form id="form" method="POST" action="{% url 'homepage:add_status' %}">
                <h2><strong>Input Status</strong></h2>
                {% csrf_token %}
                {{ status_form|crispy }}
                <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            </form>
        </div>
    </section>

    <section name="my-list" id="my-list">
        <div class="container">
            <h2 class="my-list-title">My Status</h2>

                {% if status %}
                    {% for data in status %}
                    <div class="card bg-dark text-white">

                        <div class="card-header">
                            <div class="status-list-title">
                                {{data.title}}
                            </div>
                        </div>

                        <div class="card-body">
                            <div class="status-list-date-added">
                                {{data.created_date}}
                            </div>
                            <hr>
                            <div class="status-list-description">
                                {{data.description}}
                            </div>
                        </div>

                        <div class="card-footer">
                            <a href="{% url 'homepage:del_status' data.id %}"
                            class="btn btn-danger btn-block" 
                            data-id="{{data.id}}"
                            role="button"><strong>Delete Status</strong></a>
                        </div>

                    </div>
                    <br>
                    {% endfor %}

                {% else %}          
                <div class="alert alert-danger text-center">
                    <strong>Oops!</strong> Tidak ada data status.
                </div>
                {% endif %}

            </div>
        </div>
    </section>

    <!-- Optional JavaScript -->
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
    crossorigin="anonymous"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
    crossorigin="anonymous"></script>

    <!-- Bootstrap JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
    crossorigin="anonymous"></script>

  </body>

</html>

lab9/templates/hello_lab9.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
 	
	<head>
    	
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Link to App CSS -->
    <link rel="stylesheet" href="{% static 'css/lab9_style.css' %}">

    <!-- Link to Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Link to Quicksand Font -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

    <!-- Website Page Title  -->
    <title>PPW Story 9 | Primo Giancarlo Uneputty</title>

  </head>

  <body style="background-color: #ccc;">

		<!-- Bootstrap Sticky Navbar -->
  	<nav class="navbar navbar-expand-sm bg-light navbar-light sticky-top">

  		<!-- Toggler/collapsibe Button -->
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    		<span class="navbar-toggler-icon"></span>
  		</button>

  		<!-- Navbar Links -->
  		<div class="collapse navbar-collapse" id="collapsibleNavbar">
  			<ul class="navbar-nav ml-auto" style="margin-right: 30px;">

  				<li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:index' %}" style="font-family: Quicksand; font-size: 20px;"> 
              Story 6
            </a>
          </li>

    			<li class="nav-item">
      			<a class="nav-link" href="{% url 'lab7:view_lab7' %}" style="font-family: Quicksand; font-size: 20px;"> 
      				Story 7
      			</a>
    			</li>

    			<li class="nav-item">
      			<a class="nav-link" href="{% url 'lab8:view_lab8' %}" style="font-family: Quicksand; font-size: 20px;"> 
      				Story 8
      			</a>
    			</li>

          <li class="nav-item">
            <a class="nav-link active disabled" href="{% url 'lab9:view_lab9' %}" style="font-family: Quicksand; font-size: 20px;">
              Story 9
            </a>
          </li>

  		  </ul>
  		</div>

		</nav>

    {% if user.is_authenticated %}
      <header class="text-right mb-3" style="margin-top:20px; margin-right: 20px">
        <form class="site-form" action="{% url 'lab9:logout' %}" method="post">
          {% csrf_token %}

          <button class="btn text-white" type="submit" style="background-color:#FD913C; font-family:Quicksand; font-size:20px;">
            Log Out
          </button>

        </form>
      </header>
    {% endif %}

        <!-- Bootstrap Responsive Column Span-4 -->
        <div class="container" style="margin-top:50px; margin-bottom:50px; padding-right: 5%; padding-left: 5%">
          <div class="container my-3">

            <h1 class="border-bottom mb-4" style="font-family: Quicksand; font-weight: bold; font-size: 70px;">
              <strong>HELLO THERE</br></strong>
            </h1>

            <h1 class="main-title"><strong>{{ user.username }} !</strong></h1>

          </div>
        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
    crossorigin="anonymous"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
    crossorigin="anonymous"></script>

  	<!-- Bootstrap JavaScript -->
  	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
  	integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
    crossorigin="anonymous"></script>

  </body>

</html>

lab9/templates/login_lab9.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html lang="en">
 	
 	<head>
    	
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Link to App CSS -->
    <link rel="stylesheet" href="{% static 'css/lab9_style.css' %}">

    <!-- Link to Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Link to Quicksand Font -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

    <!-- Website Page Title  -->
    <title>Login Page</title>

  </head>

  <body style="background-color: #ccc;">

		<!-- Bootstrap Sticky Navbar -->
  	<nav class="navbar navbar-expand-sm bg-light navbar-light sticky-top">

  		<!-- Toggler/collapsibe Button -->
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    		<span class="navbar-toggler-icon"></span>
  		</button>

  		<!-- Navbar Links -->
  		<div class="collapse navbar-collapse" id="collapsibleNavbar">
  			<ul class="navbar-nav ml-auto" style="margin-right: 30px;">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:index' %}" style="font-family: Quicksand; font-size: 20px;"> 
              Story 6
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'lab7:view_lab7' %}" style="font-family: Quicksand; font-size: 20px;"> 
              Story 7
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'lab8:view_lab8' %}" style="font-family: Quicksand; font-size: 20px;"> 
              Story 8
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link active disabled" href="{% url 'lab9:view_lab9' %}" style="font-family: Quicksand; font-size: 20px;">
              Story 9
            </a>
          </li>

  			</ul>
  		</div>

		</nav>

    {% if user.is_authenticated %}
    <header class="text-right mb-3" style="margin-top:20px; margin-right: 20px">
      <form class="site-form" action="{% url 'lab9:logout' %}" method="post">
        {% csrf_token %}

        <button class="btn text-white" style="background-color:#FD913C; font-family: Quicksand; font-size: 20px;" type="submit">
          Log Out
        </button>

      </form>
    </header>
    {% endif %}

    <div class="container" style="margin-top:40px; margin-bottom:40px">
      <div class="card-group">

        <div class="card text-center text-white" style="background-color:#FD913C; box-shadow: 0px 4px 14px rgba(0, 0, 0, 0.25);">
          <div class="card-body d-flex align-items-center justify-content-center">

              <h1 style="font-family: Quicksand; font-weight: bold; font-size: 50px;"> 
                <strong> "BAYAR UTANGMU SEBELUM BACOT SOAL UTANG NEGARA" </strong> <br/>
                <small class="text-muted"> ~Jokowi~ </small> <br/>
                <br/>
                <strong> "JANGAN LUPA BANYAK SHOLAT DAN BERDOA"</strong> <br/>
                <small class="text-muted"> ~Mia Khalifa~ </small>
              </h1>

          </div>
        </div>

        <div class="card" style="box-shadow: 0px 4px 14px rgba(0, 0, 0, 0.25);">

          <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">

              <li class="nav-item">
                <a class="nav-link" href="{% url 'lab9:signup' %}" style="font-family: Quicksand; font-size: 30px;">
                  SIGN UP
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" href="" style="font-family: Quicksand; font-size: 30px;">
                  LOG IN
                </a>
              </li>

            </ul>
          </div>

          <div class="container" style="margin-top:40px; margin-bottom:40px">

            <form action="{% url 'lab9:login' %}" method="post">
              {% csrf_token %}

              <fieldset class="form-group">
                <h1 style="font-family: Quicksand; font-weight: bold; font-size: 40px;"> LOG IN HERE! </h1>
                {{ form|crispy }}
              </fieldset>

              <div class="form-group" >
                <button class="btn text-white" type="submit"
                style="background-color:#FD913C; font-family:Quicksand; font-size:20px">
                  log in
                </button>
              </div>
        
            </form>

            <div class="border-top pt-3">
              <small class="text-muted">
                Don't Have An Account Yet? <a class="ml-2" href="{% url 'lab9:signup' %}">Make An Account</a>
              </small>
            </div>

          </div>
        </div>

      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
    crossorigin="anonymous"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
    crossorigin="anonymous"></script>

    <!-- Bootstrap JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
    crossorigin="anonymous"></script>

  </body>

</html>

lab9/templates/signup_lab9.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html lang="en">
 	
 	<head>
    	
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Link to App CSS -->
    <link rel="stylesheet" href="{% static 'css/lab9_style.css' %}">

    <!-- Link to Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Link to Quicksand Font -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

    <!-- Website Page Title  -->
    <title>Signup Page</title>

  </head>

  <body style="background-color: #ccc;">

		<!-- Bootstrap Sticky Navbar -->
  	<nav class="navbar navbar-expand-sm bg-light navbar-light sticky-top">

  		<!-- Toggler/collapsibe Button -->
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    		<span class="navbar-toggler-icon"></span>
  		</button>

  		<!-- Navbar Links -->
  		<div class="collapse navbar-collapse" id="collapsibleNavbar">
  			<ul class="navbar-nav ml-auto" style="margin-right: 30px;">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:index' %}" style="font-family: Quicksand; font-size: 20px;"> 
              Story 6
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'lab7:view_lab7' %}" style="font-family: Quicksand; font-size: 20px;"> 
              Story 7
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'lab8:view_lab8' %}" style="font-family: Quicksand; font-size: 20px;"> 
              Story 8
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link active disabled" href="{% url 'lab9:view_lab9' %}" style="font-family: Quicksand; font-size: 20px;">
              Story 9
            </a>
          </li>

  			</ul>
  		</div>

		</nav>

    {% if user.is_authenticated %}
    <header class="text-right mb-3" style="margin-top:20px; margin-right: 20px">
      <form class="site-form" action="{% url 'lab9:logout' %}" method="post">
        {% csrf_token %}

        <button class="btn text-white" style="background-color:#FD913C; font-family: Quicksand; font-size: 20px;" type="submit">
          Log Out
        </button>

      </form>
    </header>
    {% endif %}

    <div class="container" style="margin-top:40px; margin-bottom:40px">
      <div class="card-group">

        <div class="card text-center text-white" style="background-color:#FD913C; box-shadow: 0px 4px 14px rgba(0, 0, 0, 0.25);">
          <div class="card-body d-flex align-items-center justify-content-center">

              <h1 style="font-family: Quicksand; font-weight: bold; font-size: 50px;"> 
                <strong> "WIBU BOLEH, GOBLOG JANGAN" </strong> <br/>
                <small class="text-muted"> ~Hafidh~ </small> <br/>
                <br/>
                <strong> "NYESEL GUA NYIPTAIN WORLD WIDE WEB, MALAH DIPAKE BUAT BIKIN WEBSITE BOKEP"</strong> <br/>
                <small class="text-muted"> ~Sir Tim Bernes-Lee~ </small>
                <small class="text-muted"> (Penemu HTML & WWW) </small>
              </h1>

          </div>
        </div>

        <div class="card">

          <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">

              <li class="nav-item">
                <a class="nav-link active" href="{% url 'lab9:signup' %}" style="font-family: Quicksand; font-size: 30px;">
                  SIGN UP
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'lab9:login' %}" style="font-family: Quicksand; font-size: 30px;">
                  LOG IN
                </a>
              </li>

            </ul>
          </div>

          <div class="container" style="margin-top:40px; margin-bottom:40px">

            <form action="{% url 'lab9:signup' %}" method="post">
              {% csrf_token %}

              <fieldset class="form-group">
                <h1 style="font-family: Quicksand; font-weight: bold; font-size: 40px;"> SIGN UP HERE! </h1>
                {{ form|crispy }}
              </fieldset>

              <div class="form-group" >
                <button class="btn text-white" type="submit"
                style="background-color:#FD913C; font-family:Quicksand; font-size:20px">
                  sign up
                </button>
              </div>
        
            </form>

            <div class="border-top pt-3">
              <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'lab9:login' %}">Just Log In</a>
              </small>
            </div>

          </div>
        </div>

      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
    crossorigin="anonymous"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
    crossorigin="anonymous"></script>

    <!-- Bootstrap JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
    crossorigin="anonymous"></script>

  </body>

</html>